api: Integration with Altadefinizione, AnimeUnity and Telegram bot improvements (#288)
* Fixed issues related to TV series for the Telegram bot.

* Fixed issues related to TV series for the Telegram bot.

* feat: Integrate Telegram bot support for animeunity and altadefinizione

* api: From cb01blog to cb01new

(cherry picked from commit 477637ee5c848c5860a85939fbf6393b6cc2d3dd)

* mp4: Fix error 'set_alpn_protocols'

(cherry picked from commit ab094d0b1db21e74b8af4b5b995779dfd88ce3db)

* api: Add warning altadefinizione

(cherry picked from commit 870714ca7e88d26be1fc5530cf5ba90c69f1c296)

* Solved Unexpected error: 'int' object has no attribute 'set_alpn_protocols'

* Update series.py

---------

Co-authored-by: RubyTemple <ruby@example.com>
Co-authored-by: Lovi <62809003+Lovi-0@users.noreply.github.com>
Co-authored-by: None <62809003+Arrowar@users.noreply.github.com>